### PR TITLE
enhance SchemaObject type for composition types

### PR DESCRIPTION
**Pull request by uwinkelvos**
Composition types (allOf, anyOf, oneOf and not) are valid SchemaObjects according to the spec, but right now anything without type could not be assigned as a schema.

### CODE REVIEW

**Comment by uwinkelvos** [comment]
Hey @cdimascio! First of all thanks for all your work here! We use `express-openapi-validator` with `.ts` schema files and realized the typing of some schema objects is not correct. So this typing only change will solve this problem. Would be nice to get this into a next release! Thanks a lot!

**Comment by uwinkelvos** [comment]
Hey @cdimascio: Could you find the time to have a quick look at this change? It's  just typing level with no runtime code change and would spare typescript users a lot of insecure and redundant type assertions.

**Comment by uwinkelvos** [comment]
Hey @cdimascio! I updated my branch, status checks pass. Is there anything else I can do?

**Comment by uwinkelvos** [comment]
Hey @cdimascio, any thoughts about this?

**Comment by uwinkelvos** [comment]
Hey @cdimascio: New year next try! ;)

**Review by cdimascio — APPROVED** [review]

**Comment by cdimascio** [comment]
Will roll a new version soon

**Comment by cdimascio** [comment]
available in v.5.0.1

**Comment by uwinkelvos** [comment]
Thanks a lot this of cases where we had to "unknown-assert" parts of the schema before! :)

**Pull request merged**
