### PR TITLE
Enable default styles for array parameter delimiters

### PR DESCRIPTION
**Pull request by joodie**
Styles are not required in OpenAPI, ensure that we use the default
delimiting styles when none is provided.

### CODE REVIEW

**Comment by joodie** [comment]
Sorry about the failing "Codacy/PR Quality Review" - no idea what's going on there. Please let me know if I can help get this code accepted.

**Comment by joodie** [comment]
I've noticed a bug in this feature, will update the PR when I've fixed it.

**Comment by joodie** [comment]
Code is now in working order. Please let me know if it's a good idea to add checks for invalid `style` values when  the validator is instantiated.

**Review by cdimascio — APPROVED** [review]
Thanks a lot @joodie.
This looks good and defaults conform to https://swagger.io/docs/specification/serialization/

**Comment by cdimascio** [comment]
no worries about the codacy issue.
would you mind adding a test. 

> Code is now in working order. Please let me know if it's a good idea to add checks for invalid `style` values when the validator is instantiated.

it's a good idea idea. that said, it's ok to leave it out. we rely on Ajv for the initial validation pass. it does can't everything. that said, it fairly typical to use something like swagger editor while writing the spec, hence its often in pretty good shape by the time the validator loads it up

**Comment by cdimascio** [comment]
@all-contributors add @joodie for code and test

**Pull request merged**
