### PR TITLE
v3.0.0-alpha.1 - parse api spec asynchronously 

### PR DESCRIPTION
**Pull request by cdimascio**
@richdouglasevans @gonenduk @sheldhur @scriptify @comino would very much appreciate your feedback on the following. I am considering changing the API in v3 and making the lib fully async.

To see how usage might change see
- The Usage section of the [README](https://github.com/cdimascio/express-openapi-validator/blob/fc27c2cf92daf1b7d90ff0974374dd66affe3cd1/example/README.md)
- The [example app](https://github.com/cdimascio/express-openapi-validator/blob/fc27c2cf92daf1b7d90ff0974374dd66affe3cd1/example/app.js#L26)

The motivation for this PR is to remove the dependency on the [deasync](https://github.com/abbr/deasync) library. In order to do so, the parsing and json-ref resolution (spec splitting) will now occur asynchronously. This impacts the API surface as the `install` method can no longer be syncrhonous. Ultimately, this means routes/middleware functions must be applied once the promise settles (async/await can be used) or via a callback.

**Notes:**
- Remove dependency on `deasync`
- These changes modify the API surface and constitute a breaking change

  **`install`** returns a Promise<Express.Application> instead of void

  **old**
  ```javascript
  new OpenApiValidator({
    apiSpec: './example.yaml',
  }).install(app);

  // custom routes
  app.get(...)

  app.use(errorHandler)
  // ...
  ```

  **new** 
  ```javascript
  new OpenApiValidator({
    apiSpec: './example.yaml',
  })
  .install(app)
  .then(() => {
    // custom routes
    app.get(...)

    app.use(errorHandler)
    // ...
  });
  ```

### CODE REVIEW

**Comment by scriptify** [comment]
I think removing deasync will be a huge win! There's just one thing I not sure about: Using it in a serverless way. If someone for example uses [aws-serverless-express](https://github.com/awslabs/aws-serverless-express) or something similar, there could be a problem with routes not being setup when the request comes in. Any thoughts about this? Is this library even inteded to be used in a serverless way? I could do a quick test if so.

**Comment by cdimascio** [comment]
this will not be a problem. node behaves in an asynchronous manner, hence all js based libs, frameworks, etc do as well. all in all, there is nothing technical that prevents this from working in a serverless environment.

note that endpoints to be registered after the install's promise resolves e.g. in `.then` (see below). because of this, it is impossible for one these endpoints to handle a request prior to validator setup/install. in the absolutely worst case, a request(s) that comes in prior to validation being initialized will be queued on the promise. 

```javascript
new OpenApiValidator({
  apiSpec: './example.yaml',
})
.install(app)
.then(app => {
  // add routes to validate here <----------
});
```

hope this helps

**Comment by cdimascio** [comment]
on a tangential note, i can support both sync and async behavior

**Async**
To install:
```shell
npm install express-openapi-validator
```

To use:

```javascript
await new OpenApiValidator({
  apiSpec: './example.yaml',
}.install(app)
```

**Sync**
To install:
```shell
npm install express-openapi-validator deasync
```

To use:

```javascript
new OpenApiValidator({
  apiSpec: './example.yaml',
}.installSync(app)
```

Thoughts?

**Comment by scriptify** [comment]
Yea that's what I meant, I'm not doubting that it works in a serverless environment, but requests may come in prior the installation, because serverless functions (at least when cold starting) don't wait for your endpoints being available.

I like the option of 2 different install modi! People could opt-in for the sync version if the asynchronicity is causing any problems.

**Comment by cdimascio** [comment]
@scriptify 

a version of v3 alpha is available on npm. please give it a try. it makes `deasync` optional in that it must be installed explicitly. it is only needed if using the lib synchronously.

The alpha version is available now: "express-openapi-validator": "^3.0.0-alpha.1"

See the [alpha readme](https://github.com/cdimascio/express-openapi-validator/tree/async_1)) for details

**Comment by cdimascio** [comment]
Addresses #162, #159, and #151

**Comment by gonenduk** [comment]
Since deasync is a peer - not installing it gives a warning in npm:
`npm WARN express-openapi-validator@3.0.0-alpha.2 requires a peer of deasync@^0.1.16 but none is installed. You must install peer dependencies yourself.`
Is there a way to make it optional so we don't get the error?

**Comment by cdimascio** [comment]
Unfortunately, there is not a good solution. Npm, `optionalDependencies` are automatically installed unless the user explicitly **opts-out** by specifying `npm install --no-optional`. `peerDependencies` (which I'm currently using)  are **opt-in** which is nice, but emit the warning (not so nice). Ultimately, we want `optionalPeerDependencies`, but that does not exist.

**Comment by cdimascio** [comment]
looks like a peer dep that is not installed can cause problems with shrinkwrap and potentially other tools. i'm going to drop support for synchronous install. if there is demand i'll consider it as a supplementary package.

**Pull request merged**
