### PR TITLE
fix: ensure JSON in form-data field is parsed IFF it is an object or array

### PR DESCRIPTION
**Pull request by ownagedj**
This commit fixes a problem with non primitives values in multipart/form-data field(s).

### CODE REVIEW

**Comment by ownagedj** [comment]
Hi, some time has passed and this is still an issue in version 5.
Could you please merge this PR?

**Review by cdimascio — APPROVED** [review]
Looks good thanks. Will get a new version out soon

**Comment by gitschwifty** [comment]
hey not to bug you @cdimascio but would be great if we could get a release with this fix 🙏

**Comment by cdimascio** [comment]
Will have it out momentarily

**Comment by cdimascio** [comment]
Available in v5.0.2

**Comment by gitschwifty** [comment]
Awesome, thank you man!

**Pull request merged**
