### PR TITLE
Better handling of MulterError

### PR DESCRIPTION
**Pull request by jy95**
Proposal for a better handling of these multer errors

### CODE REVIEW

**Comment by jy95** [comment]
As the typings definition for "MulterError" are missing, we need to think where I could store the definition of it : 

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39263

**Comment by cdimascio** [comment]
@jy95 i've modified you PR with type definitions for multer. i borrowed them from the issue you referenced. please have a look to see if this change provides what you're looking for

**Comment by jy95** [comment]
LGTM : now all that remains is to fix this compilation error of the travis build ...

**Comment by cdimascio** [comment]
@jy95 will get this merged and roll a new version

**Comment by cdimascio** [comment]
Thanks for the PR!

**Comment by cdimascio** [comment]
fixes #167

**Comment by cdimascio** [comment]
@all-contributors add @jy95 for code

**Pull request merged**
